[package]
name = "rust-quatum-simulator"
version = "0.1.0"
authors = ["Ismael Faro <Ismael.Faro1@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
